### ISSUE TITLE
this._prunedBabelOptions is not a function

### ISSUE THREAD

**Issue by lolmaus** [isleofcode/ember-cli-asset-sizes-shim#6]
https://travis-ci.org/bread-maker/bread-maker-ember-frontend/builds/257435506

```
this._prunedBabelOptions is not a function
TypeError: this._prunedBabelOptions is not a function
    at EmberApp._processedTemplatesTree (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli-asset-sizes-shim/lib/shim-app.js:191:29)
    at EmberApp.appAndDependencies (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1109:26)
    at EmberApp.hookedJavascriptTree (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli-asset-sizes-shim/lib/shim-app.js:249:30)
    at EmberApp.toArray (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1672:12)
    at EmberApp.toTree (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1694:38)
    at module.exports (/home/travis/build/bread-maker/bread-maker-ember-frontend/ember-cli-build.js:83:14)
    at Builder.setupBroccoliBuilder (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/home/travis/build/bread-maker/bread-maker-ember-frontend/node_modules/ember-cli/lib/models/command.js:243:46)
error Command failed with exit code 1.
```

Ember CLI 2.14.0

**Comment by lolmaus** [comment]
When running `ember build` or `ember asset-sizes`.

**Comment by g-cassie** [comment]
Same in ember-cli 2.13.1

**Comment by g-cassie** [comment]
It's related to this:
https://github.com/ember-cli/ember-cli/commit/bf757cc68ca02212c4aed1e28f46593da475a713#diff-392bb207fea8bcbeb4a084bb445f7cc7

Looks like `this[INTERNAL_BABEL_OPTIONS]()` would work...
